#!/usr/bin/env bash
# Installs nginx server and configures the sever to listen on port 80
# Curl get request returns a page that contains 'hello World!'
sudo apt-get update
sudo apt-get install -y nginx
sudo mkdir -p /var/www/default/html/index
echo "Hello World!" > /var/www/default/html/index.html
sudo service nginx restart
