#!/usr/bin/env bash
# Installs nginx server and configures the sever to listen on port 80
# Curl get request returns a page that contains 'hello World!'
sudo apt-get update
sudo apt-get install -y nginx
sudo mkdir -p /var/www/html
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html >/dev/null
sudo service nginx restart
