#!/usr/bin/env bash
# configures nginx server so that /redirect_me redirects to another page
# redirects to https://www.youtube.com/watch?v=QH2-TGUlwu4
# http 301. moved permanently


# update package index files and install nginx server
sudo apt-get update -y -qq && sudo apt-get install nginx -y

# starting nginx server 
sudo service nginx start

# allow nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to webstie files for easy editing
sudo chown -R "$USER":"$USER"  /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# creating new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Setting u /redirect_me  to a youtube video
sudo sed -i '24c\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Setup 404 page file and content
echo "Ceci n'est pas une page" | tee /var/www/html/error_404.html

# Setup 404 configuration
sudo sed -i '25c\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default

# Restart nginx 
sudo service nginx restart
echo -e "\nCompleted.\n"
