#!/usr/bin/env bash
# Install a load balancer HA-PROXY
# Configures the load balance to suite desired configurations
# Ensure that the haProxy can be managed via init script

echo -e "\nHA-PROXY configration beggins\n"

function install() {
	command -v "$1"

	#shellcheck disable=SC2181
	if [ $? -ne 0 ]; then
		echo -e "Installing haproxy\n"
		sudo apt-get update -y -qq
		sudo apt-get install -y "$1" -qq
		echo -e "HA-PROXY is installation successful\n"
	else
		echo -e  "HA-PROXY is already installed\n"
	fi
}

echo -e "check if haproxy is installed ....\n"
install haproxy # install haproxy

# Backup the current configuration
echo -e "Creating abackup of the cureent configuration\n"
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bckp

server="\
	global
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

        # Default SSL material locations
        ca-base /etc/ssl/certs
        crt-base /etc/ssl/private

        # See: https://ssl-config.mozilla.org/#server=haproxy&server-version=2.0.3&config=intermediate
        ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
        ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
        ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http


frontend chifundo_365_frontend
        bind *:80
        default_backend chifundo_365_backend

backend chifundo_365_backend
        balance roundrobin
        server web-01 34.224.16.226:80 check
        server web-02 54.173.111.119:80 check
"
echo -e "updating the configuration file .....\n"
echo "$server" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

echo -e "configuring haproxy to be managed by an init script\n"
echo -e "ENABLED=1" | sudo tee -a /etc/default/haproxy > /dev/null

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	echo -e "haproxy not running. starting it ...\n"
	sudo service haproxy start
else
	echo -e "haproxy already running. restarting it\n"
	sudo service haproxy restart
fi

echo -e "DONE!!\n"


