#!/usr/bin/env bash
# Process manaager for 'manage_my_process' instance

if [[ -z $1 ]]; then
	echo "Usage: manage_my_process {start|stop|restart}"
else
	case $1 in
	"start")
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started";;
	"stop")
	kill -9 "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
	echo "manage_my_process stopped";;
	"restart")
	kill -9 "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process restarted";;
	esac
fi		
