#!/usr/bin/env bash
# Displays 'To infinity and beyond' indefinetely with a sleep in each iteration
# Displays 'I am invicible!!!' when receiving s SIGTERM signal
trap "echo I am invincible!!!" SIGTERM
COUNT=0
while (( COUNT < 10 )); do
	echo "to infinity and beyond"
	sleep 2
done
