#!/usr/bin/env bash
# displays "Best School" ten times and a "Hi" on line 10

counter=0
while [ $counter -lt 10 ]; do
	echo "Best School"
	if [[ $counter == 8 ]]; then
		echo "Hi"
	fi
	((counter++))
done

counter=10
