#!/usr/bin/env bash
# displays numbers from 1 to 20, if number is 4 it print "bad luck from china" if 9 "bad luck from Japan", 17 "bad luck from italy
x=1
while [[ $x -lt 21 ]]; do
	echo $x
	case $x in
	4)
	echo "bad luck from China";;
	9)
	echo "bad luck from Japan";;
	17)
	echo "bad luck from Italy";;
	esac
	((x++))
done
