#!/usr/bin/env bash
# displays the content of a directory in a list format
# Where only part of the name after the dash is displayed
for file in *; do
	if [[ ! "$file" =~ ^\..* ]]; then
		name=$(echo "$file" | cut -d '-' -f 2-)
		echo "$name"
	fi
done
